version: '3.6'
services:
  couchdb:
    build: ./Couchdb
    restart: always
    volumes:
      - type: bind
        source: /tmp/couch/data
        target: /opt/couchdb/data
#    env_file:
#      - docker/couch/env.docker
    ports:
      - target: 5984
        published: 5984
        protocol: tcp
        mode: host
    networks:
      - app-init

  init:
    build: ./Init
    depends_on:
      - couchdb
    command: sh -c './wait-for.sh couchdb:5984 -- ./init.sh'
    restart: "no"
    networks:
      - app-init

  app:
    build: ./App
    restart: "no"
    depends_on:
      - couchdb
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

networks:
  app-init:
